system:
  debug: True
  secret: RZ1PcBzqbfQ9fkVqXWLiS4ZyeXihVYIN
  prefix:
  port: 8090
  login_url:
  static:
  templates:
  static_url_prefix:
  xsrf_cookies: True
  auto_reload: True
  jwt_expire: 7*24*3600
  public_key:
  private_key:
  aes_key:
  aes_iv:

middleware:

database:
  hostname:
  port:
  database:
  username:
  password:

collector:
  area-url: "http://lab.isaaclin.cn/nCoV/api/area"
  overall-url: "http://lab.isaaclin.cn/nCoV/api/overall"
  news-url: "http://lab.isaaclin.cn/nCoV/api/news"
  timer: 120

WX:
  token: RZ1PcBzqbfQ9fkVqXWLiS4ZyeXihVYIN
  app_id: wxcb5b5fa28f55339a
  app_secret: 0daf1d7fa1c5a5b184e1d99fdc4b4db0